/*
 * CDotVewer.cpp
 *
 *  Created on: Feb 21, 2014
 *      Author: andy
 */

#include "gimcs/CDotViewer.h"
#include "gimcs/Agent.h"
#include "gimcs/Storage.h"

namespace gimcs
{

CDotViewer::CDotViewer() :
        last_state(INVALID_STATE), last_action(INVALID_ACTION)
{
}

CDotViewer::CDotViewer(Storage *sg) :
        DotViewer(sg), last_state(INVALID_STATE), last_action(INVALID_ACTION)
{
}

CDotViewer::~CDotViewer()
{
}

void CDotViewer::Show()
{
    int re = storage->Connect();
    if (re != 0)    // connect failed
    {
        WARNNING("DotViewer CleanShow(): connect to storage failed!\n");
        return;
    }

    printf(
            "/* This is the dot file of agent memory automaticlly generated by DotViewer */\n\n");

    // generate dot syntax
    printf("digraph %s \n{\n", storage->GetMemoryName().c_str());

    // memory info
    struct Memory_Info *memif = storage->GetMemoryInfo();
    if (memif != NULL)
    {
        printf(
                "label=\"memory %s\\ndiscount rate: %.2f, threshold: %.2f, #states: %ld, #links: %ld\"\n",
                storage->GetMemoryName().c_str(), memif->discount_rate,
                memif->threshold, memif->state_num, memif->lk_num);
        // store last status
        last_state = memif->last_st;
        last_action = memif->last_act;
        free(memif);    // free it, the memory struct are not a substaintial struct for running, it's just used to store meta-memory information
    }
    else
    {
        printf("Memory not found in storage!\n");
        printf("}\n");    // digraph
        storage->Close();
        return;
    }

    // states info
    printf("node [color=black,shape=circle]\n");
    printf("rank=\"same\"\n");
    // print states info
    Agent::State st = storage->FirstState();
    while (st != INVALID_STATE)    // get state value
    {
        struct State_Info_Header *stif = storage->GetStateInfo(st);
        if (stif != NULL)
        {
            CleanDotStateInfo(stif);
            free(stif);
            st = storage->NextState();
        }
        else
            ERROR("Show(): state: %ld information is NULL!\n", st);
    }
    printf("}\n");    // digraph
    storage->Close();
}

void CDotViewer::CleanDotStateInfo(const struct State_Info_Header *sthd) const
{
    /* generated state example:
     *
     * st9 [label="9"]
     *
     * st9 -> st8 [label="<0, -1>"]
     * st9 -> st10 [label="<0, 1>"]
     */
    if (sthd == NULL) return;

    printf("\nst%ld [label=\"%ld\"]\n", sthd->st, sthd->st);

    unsigned char *stp = (unsigned char *) sthd;    // use point stp to travel through each subpart of state
    unsigned char *atp;
    // environment action information
    stp += sizeof(struct State_Info_Header);    // point to the first act
    int anum;
    for (anum = 0; anum < sthd->act_num; anum++)
    {
        Action_Info_Header *athd = (Action_Info_Header *) stp;

        atp = stp;
        atp += sizeof(Action_Info_Header);    // point to the first eat of act
        int i;
        for (i = 0; i < athd->eat_num; i++)    // copy every eat of this act
        {
            EnvAction_Info *eaif = (EnvAction_Info *) atp;
            printf("st%ld -> st%ld [label=\"<%ld, %ld>\"]\n", sthd->st,
                    eaif->nst, athd->act, eaif->eat);

            atp += sizeof(EnvAction_Info);    // point to the next eat
        }
        stp += sizeof(Action_Info_Header)
                + athd->eat_num * sizeof(EnvAction_Info);    // point to the next act
    }
}

} /* namespace gimcs */
